---
- name: Deploy an SNO cluster
  import_playbook: vgpu-openshift-playbook/sno.yml

- name: Deploy Riva on the SNO cluster
  hosts: localhost
  gather_facts: no
  roles:
    - name: riva_server
      vars:
        cluster_api_vip: "{{ assisted_cluster.api_vip }}"

