---
- name: Deploy an SNO cluster
  import_playbook: gpu-openshift-playbook/sno.yml
  vars:
    temp_directory: "{{ playbook_dir }}/tmp"

- name: Deploy Riva on the SNO cluster
  hosts: localhost
  gather_facts: no
  roles:
    - name: riva_server
      vars:
        cluster_api_vip: "{{ assisted_cluster.api_vip }}"
